<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitc5629b5540e8fbb490f9d4322dd07d6f
{
    public static $prefixLengthsPsr4 = array (
        'C' => 
        array (
            'Composer\\Installers\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Composer\\Installers\\' => 
        array (
            0 => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers',
        ),
    );

    public static $fallbackDirsPsr4 = array (
        0 => __DIR__ . '/../..' . '/admin/includes/lib/Wp-admin-notice',
    );

    public static $prefixesPsr0 = array (
        'C' => 
        array (
            'Composer\\CustomDirectoryInstaller' => 
            array (
                0 => __DIR__ . '/..' . '/idct/composer-custom-directory/src',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitc5629b5540e8fbb490f9d4322dd07d6f::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitc5629b5540e8fbb490f9d4322dd07d6f::$prefixDirsPsr4;
            $loader->fallbackDirsPsr4 = ComposerStaticInitc5629b5540e8fbb490f9d4322dd07d6f::$fallbackDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInitc5629b5540e8fbb490f9d4322dd07d6f::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
